version: '3'

services:
  mysql:
    image: mysql:8.0.22
    tmpfs: /var/lib/mysql:rw
    command:
      --default-time-zone=+8:00
      --innodb-buffer-pool-size=20M
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_DATABASE=spring_base"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"
  mongo:
    image: mongo
    restart: always
    container_name: spring_base_mongo_container
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: spring_base
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
