version: '3'

services:
  mysql_shop:
    image: mysql:8.0.22
    environment:
      - "MYSQL_DATABASE=spring_base"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"

  shop:
    build:
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=mysql_shop
    depends_on:
      - mysql_shop
