name: CI

on: [push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Execute Unit Test task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test

    - name: Execute Integration Test task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: integrationTest
